version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: secretfriend
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: secret-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secretfriend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: